# Generated by Django 6.0.3 on 2026-03-21 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adzuna_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('country', models.CharField(default='us', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('redirect_url', models.URLField()),
                ('category', models.CharField(blank=True, max_length=200)),
                ('skill_tags', models.JSONField(default=list)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('matched_role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_listings', to='skills.occupationrole')),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['country', 'category'], name='jobs_joblis_country_b4fee2_idx'), models.Index(fields=['expires_at'], name='jobs_joblis_expires_3041fb_idx'), models.Index(fields=['matched_role'], name='jobs_joblis_matched_ae65b1_idx')],
            },
        ),
    ]
