# Generated by Django 6.0.3 on 2026-04-05 05:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused')], default='active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('target_role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_goals', to='skills.occupationrole')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_goal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Career Goal',
            },
        ),
        migrations.CreateModel(
            name='LearningStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('technical', 'Technical Skill'), ('soft', 'Soft Skill'), ('certification', 'Certification'), ('advanced', 'Advanced Concept')], default='technical', max_length=15)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Not Started'), ('learning', 'In Progress'), ('done', 'Completed')], default='pending', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='roadmap.careergoal')),
            ],
            options={
                'ordering': ['order', 'skill_name'],
            },
        ),
    ]
