# Generated by Django 6.0.3 on 2026-04-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('platform', models.CharField(choices=[('coursera', 'Coursera'), ('udemy', 'Udemy'), ('youtube', 'YouTube'), ('freecodecamp', 'freeCodeCamp'), ('edx', 'edX'), ('linkedin', 'LinkedIn Learning'), ('pluralsight', 'Pluralsight'), ('kaggle', 'Kaggle'), ('google', 'Google'), ('microsoft', 'Microsoft'), ('other', 'Other')], max_length=20)),
                ('url', models.URLField(max_length=500)),
                ('skill_tags', models.CharField(help_text='Comma-separated skill names this course covers', max_length=500)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=15)),
                ('duration_hours', models.PositiveSmallIntegerField(default=0, help_text='Estimated hours to complete')),
                ('is_free', models.BooleanField(default=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-rating', 'title'],
                'indexes': [models.Index(fields=['skill_tags'], name='courses_cou_skill_t_3b5c07_idx'), models.Index(fields=['platform'], name='courses_cou_platfor_264bd4_idx')],
            },
        ),
    ]
