# Generated by Django 6.0.3 on 2026-04-05 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0002_parsededucation_year_resume_github_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parsededucation',
            options={'ordering': ['-year', '-id']},
        ),
        migrations.AlterModelOptions(
            name='parsedexperience',
            options={'ordering': ['-id']},
        ),
    ]
