# Generated by Django 6.0.3 on 2026-03-21 03:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OccupationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('onet_code', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('csv', 'CSV Seed'), ('onet', 'O*NET API')], default='csv', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RequiredSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('soft', 'Soft Skill'), ('advanced', 'Advanced Concept'), ('certification', 'Certification')], default='technical', max_length=15)),
                ('importance', models.PositiveSmallIntegerField(default=50)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_skills', to='skills.occupationrole')),
            ],
            options={
                'ordering': ['-importance', 'name'],
                'unique_together': {('role', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SkillGapReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_percentage', models.FloatField(default=0)),
                ('matched_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('missing_certifications', models.JSONField(default=list)),
                ('missing_advanced', models.JSONField(default=list)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.occupationrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gap_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'role')},
            },
        ),
    ]
