# Generated by Django 6.0.3 on 2026-03-21 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobDataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=20, unique=True)),
                ('skills', models.TextField()),
                ('years_of_experience', models.PositiveSmallIntegerField()),
                ('predicted_job_title', models.CharField(max_length=100)),
                ('company_name', models.CharField(blank=True, max_length=100)),
                ('company_location', models.CharField(blank=True, max_length=100)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('salary_usd', models.PositiveIntegerField(default=0)),
                ('education_level', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['job_id'],
            },
        ),
        migrations.CreateModel(
            name='TrainedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm', models.CharField(choices=[('random_forest', 'Random Forest'), ('naive_bayes', 'Naive Bayes'), ('svm', 'SVM (LinearSVC)'), ('neural_net', 'Neural Network (MLP)')], max_length=30)),
                ('artifact', models.BinaryField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='ModelPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('training_samples', models.PositiveIntegerField(default=0)),
                ('model', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='ml.trainedmodel')),
            ],
        ),
    ]
